### PR TITLE
Update gitignore to ignore Google API credentials

### PR DESCRIPTION
**Pull request by benjimarshall**

### CODE REVIEW

**Review by FridaTveit — APPROVED** [review]
Looks good 🙂 Probably worth adding a README.md file which explains how to create the credentials file and where to get the credentials from. And any other useful info a new dev would need 🙂

**Comment by benjimarshall** [comment]
Yes I'll write one at some point soon!

**Comment by FridaTveit** [comment]
Writing a README.md might be something it would be good for @timleachsw to do, since he's just ramped up so should know what he needed to do while ramping up? What do you both think? 🙂

**Comment by timleachsw** [comment]
Yes I can definitely do that!!

**Pull request merged**
